service: financial-data-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1  # Tokyo region, change as needed
  stage: ${opt:stage, 'dev'}
  environment:
    FINANCIAL_DATA_LOGIN: ${env:FINANCIAL_DATA_LOGIN}
    FINANCIAL_DATA_PASSWORD: ${env:FINANCIAL_DATA_PASSWORD}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: "*"
  httpApi:
    cors:
      allowedOrigins:
        - "*"  # 生產環境建議限制特定域名
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: '*'
    timeout: 30
    memorySize: 512
    environment:
      NODE_ENV: ${self:provider.stage}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

