service: cbonds-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1  # Tokyo region, change as needed
  stage: ${opt:stage, 'dev'}
  environment:
    CBONDS_LOGIN: ${env:CBONDS_LOGIN}
    CBONDS_PASSWORD: ${env:CBONDS_PASSWORD}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /api/{proxy+}
          method: '*'
    timeout: 30
    memorySize: 512

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
